version: '3.8'

services:
  spotsaver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SPOTIFY_SP_DC=${SPOTIFY_SP_DC}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/spotify/token"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 